[pytest]

# Diretório onde estão os testes
testpaths = tests

# Nome padrão dos arquivos de teste
python_files = test_*.py

# Nome padrão das classes de teste
python_classes = Test*

# Nome padrão das funções de teste
python_functions = test_*

# Opções padrão
addopts =
    -v
    